server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Разрешить доступ ко всем файлам (осторожно в продакшене!)
    location ~ \.(html|css|js|png|jpg|jpeg|gif|ico|svg|ttf|woff|woff2)$ {
        root /usr/share/nginx/html;
        access_log off;
        expires max;
    }
}